appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: X12vMlGpz1KLK3ASmJx1m4kBqBFbeROfsXjR7e6+aY8FnC07PPtx1OjZLtq30omIrPhw4tmUKNvP96vB7ER0TW2YUNlSX4ZPPI4KrhqKWri0Mohwd8In8h1RKYg+QT4qAHLILVcjbEFvC9aP48JZ3L31LnQkXTRR8G1kgdb2uLfa9u2R+H4Yn4cK1dSVffRRHICHV+oN1Sq6YtLffA/INP2HV5v43zqc+HiudRS+V0JZ0etQzGpjqq1Pt1TH5IBRuKzeM7iC07yj+9b1qVdbAGlOURUOeCU2cn87GKRhj5xg2tJyQOebZKa/OPBQdizdPit6da3B309UFlaSGU+cFCM9FF2ooI5VLOmpgWnkKpk6n8BHGmiJSFlrhwT9fXf3RxvzIjId2DtfUwOl9WYja51iPkcwq0vKNPxqnvBxzIaWDt35A6XI8Y19Y9/sRdSnEdEbVDyCE/MWF4cYAt5irhiFsSKFN0jxIuCIV88HwV/6Tfqvka3SFTNjV21Hy2pwT9GozFC9Qeou1xFw2kXMuO+7o/XlDWwv8JK+4qFdc1UcV3Qa8lUbC4Jrcqk09g5cgbzBdLm20/VrdevRg2P6xA5A20+UagnKj29tcQS0QCPgVScIjJAjwbu5txDG4lL4nJrV5fF1JllX8I0CsqVmX+9v1awkpyRfDuhu5JunYOw=}
